export const itemTypes = [
  "mu",
  "sparkle",
  "moneyBag",
  "pig",
  "sheep",
  "rooster",
  "meat",
  "poop",
  "gift",
  "santaClaus",
  "police",
  "axe",
  "gear",
  "vampire",
  "blood",
  "soap",
  "water",
  "slotMachine",
  "seeding",
] as const;

export type ItemType = typeof itemTypes[number];

export const itemNames: Record<ItemType, string> = {
  mu: "🈚️",
  moneyBag: "💰",
  pig: "🐖",
  sheep: "🐑",
  rooster: "🐓",
  meat: "🍖",
  poop: "💩",
  sparkle: "✨",
  gift: "🎁",
  santaClaus: "🎅",
  police: "👮",
  axe: "🪓",
  gear: "⚙️",
  vampire: "🧛",
  blood: "🩸",
  soap: "🧼",
  water: "💧",
  slotMachine: "🎰",
  seeding: "🌱",
};
